# Generated by Django 5.2 on 2026-04-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fidpha", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
