# Generated by Django 5.2 on 2026-04-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fidpha", "0002_alter_contract_end_date_alter_contract_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
