# Generated by Django 5.2 on 2026-04-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fidpha", "0004_account_created_at_account_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="last_sale_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="last_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="contract_product",
            unique_together={
                ("contract", "external_designation"),
                ("contract", "product"),
            },
        ),
    ]
