# Generated by Django 5.2 on 2026-04-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fidpha", "0006_roleprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract_product",
            name="points_per_unit",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="contract_product",
            name="target_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
