# Generated by Django 5.2 on 2026-04-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fidpha", "0007_add_points_and_target_to_contract_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ppv",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
