# Generated by Django 5.2 on 2026-05-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fidpha", "0009_alter_contract_product_points_per_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract_product",
            name="points_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Points multiplier per dirham of PPV. Default 1 = 1 pt/MAD.",
                max_digits=6,
            ),
        ),
    ]
