# Generated by Django 5.2 on 2026-04-20 10:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_apitoken_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="APITokenUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "called_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("endpoint", models.CharField(blank=True, default="", max_length=255)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="api.apitoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Usage Log",
                "ordering": ["-called_at"],
            },
        ),
    ]
