# Generated by Django 5.2 on 2026-05-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0001_systemconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
