# Generated by Django 5.2 on 2026-04-18 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0002_apitoken_created_by"),
        ("fidpha", "0005_contract_last_sale_datetime_contract_last_sync_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(max_length=100)),
                ("account_code", models.CharField(max_length=50)),
                ("external_designation", models.CharField(max_length=255)),
                ("sale_datetime", models.DateTimeField()),
                ("creation_datetime", models.DateTimeField()),
                ("quantity", models.PositiveIntegerField()),
                ("ppv", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contract_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_imports",
                        to="fidpha.contract_product",
                    ),
                ),
                (
                    "inserted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.apitoken",
                    ),
                ),
            ],
            options={
                "db_table": "SaleImport",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_datetime", models.DateTimeField()),
                ("creation_datetime", models.DateTimeField()),
                ("quantity", models.PositiveIntegerField()),
                ("ppv", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="fidpha.contract_product",
                    ),
                ),
                (
                    "inserted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.apitoken",
                    ),
                ),
                (
                    "sale_import",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale",
                        to="sales.saleimport",
                    ),
                ),
            ],
            options={
                "db_table": "Sale",
            },
        ),
        migrations.AddIndex(
            model_name="saleimport",
            index=models.Index(
                fields=["batch_id"], name="SaleImport_batch_i_5ecd83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleimport",
            index=models.Index(
                fields=["account_code", "status"], name="SaleImport_account_434aed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["contract_product", "sale_datetime"],
                name="Sale_contrac_a435d0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sale",
            unique_together={("contract_product", "sale_datetime")},
        ),
    ]
