# Generated by Django 5.2 on 2026-04-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="saleimport",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
