# Generated by Django 5.2 on 2026-04-28 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_add_status_to_sale"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sale",
            unique_together=set(),
        ),
    ]
