# Generated by Django 5.2 on 2026-04-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_remove_sale_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="product_ppv",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
