# Generated by Django 5.2 on 2026-04-29 16:37

from django.db import migrations


def backfill_product_ppv(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    sales_to_update = []
    for sale in (
        Sale.objects
        .filter(product_ppv__isnull=True)
        .select_related("contract_product__product")
    ):
        ppv = sale.contract_product.product.ppv
        if ppv is not None:
            sale.product_ppv = ppv
            sales_to_update.append(sale)
    if sales_to_update:
        Sale.objects.bulk_update(sales_to_update, ["product_ppv"])


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_add_sale_product_ppv"),
    ]

    operations = [
        migrations.RunPython(backfill_product_ppv, migrations.RunPython.noop),
    ]
